apiVersion: v1
kind: Service
metadata:
  name: mc-service
spec:
  type: NodePort
  selector:
    cloud-group: proxy
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25577
      nodePort: 30009